/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include<led.h>
#include<FreeRTOS.h>
#include<FreeRTOSConfig.h>
#include<task.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Create four task functions vLedTask1(), vLedTask2(), vLedTask3() and vLedTask4()
//which will toggle four different LEDs with different rate. Create four real-time
//tasks to execute these functions.

void vGreen_led_blinkTask(void *pvParam)
{
	portTickType pxPreviousWakeUpTime = xTaskGetTickCount();
	while(1)
	{
		led_toggle(LED_GREEN);
		vTaskDelayUntil(&pxPreviousWakeUpTime,300/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

void vRed_led_blinkTask(void *pvParam)
{
	portTickType pxPreviousWakeUpTime = xTaskGetTickCount();
	while(1)
	{
		led_toggle(LED_RED);
		vTaskDelayUntil(&pxPreviousWakeUpTime,300/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

void vBlue_led_blinkTask(void *pvParam)
{
	portTickType pxPreviousWakeUpTime = xTaskGetTickCount();
	while(1)
	{
		led_toggle(LED_BLUE);
		vTaskDelayUntil(&pxPreviousWakeUpTime,300/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

void vOrange_led_blinkTask(void *pvParam)
{
	portTickType pxPreviousWakeUpTime =xTaskGetTickCount();
	while(1)
	{
		led_toggle(LED_ORANGE);
		vTaskDelayUntil(&pxPreviousWakeUpTime,300/portTICK_RATE_MS);
	}
		vTaskDelete(NULL);
}

int main()
{
	led_init(LED_GREEN);
	led_init(LED_RED);
	led_init(LED_ORANGE);
	led_init(LED_BLUE);


	xTaskCreate(vGreen_led_blinkTask,"Task1", configMINIMAL_STACK_SIZE, NULL,5,NULL);
	xTaskCreate(vRed_led_blinkTask,"Task2", configMINIMAL_STACK_SIZE, NULL,4,NULL);
	xTaskCreate(vBlue_led_blinkTask,"Task3", configMINIMAL_STACK_SIZE, NULL,3,NULL);
	xTaskCreate(vOrange_led_blinkTask,"Task4", configMINIMAL_STACK_SIZE, NULL,2,NULL);



	vTaskStartScheduler();



	while(1);
}

